# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09

Description: creation of aws ec2 instance and attach a sec group to it 

Parameters:
    InstanceType:
      Description: "The EC2 instance type of general purpose"
      Type: String

    AMI:
      Description: AMI to use for our base image
      Type: AWS::EC2::Image::Id

    EnvironmentName:
      Description: An environment name that will be prefixed to resource names
      Type: String

Resources:
  
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup

      KeyName: ssh_server_test	
      
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
  
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0 